In [2]:
import numpy as np
# from scipy.stats import multivariate_normal

In [5]:
mu = np.array([0, 0])
sigma = np.array([[1, 0], [0, 1]])

x = np.array([[1, 2],[3,6],[6,-2]])
print(multivariate_normal.pdf(x, mean=mu, cov=sigma))

[1.30642333e-02 2.69273918e-11 3.28042787e-10]


In [38]:
num_mixture = 3
mixture_weight = np.array([1] * num_mixture)

mixture_mu = np.array([[3,3], [2,2], [-3,-3]], dtype=float)
cov_params = np.array([np.eye(2)] * num_mixture)


x = np.array([[1, 2],[3,6],[6,-2],[0,0]])
print(mixture_weight.shape)
g = np.array([multivariate_normal.pdf(x, mean=mixture_mu[i], cov=cov_params[i]) for i in range(num_mixture)])
print(g.shape)
print(mixture_weight @ g)
print(g)


(3,)
(3, 4)
[1.09596586e-01 1.80043471e-03 2.44994448e-08 2.95430703e-03]
[[1.30642333e-02 1.76805171e-03 6.58891552e-09 1.96412803e-05]
 [9.65323526e-02 3.23829967e-05 1.79105293e-08 2.91502447e-03]
 [1.98968008e-10 6.24586999e-27 2.48740426e-19 1.96412803e-05]]


In [43]:
a = np.arange(10).reshape(5, 2)
w = np.array([1, 2, 3, 4, 5])
print(a.T)
print(w * a.T)
print(np.dot(w*a.T, a))

s = np.zeros((2, 2))
for i in range(5):
    s += w[i] * np.outer(a[i], a[i])
print(s)

[[0 2 4 6 8]
 [1 3 5 7 9]]
[[ 0  4 12 24 40]
 [ 1  6 15 28 45]]
[[520 600]
 [600 695]]
[[520. 600.]
 [600. 695.]]


In [ ]:
[[1.30642333e-02 9.65323526e-02 1.98968008e-10]
 [1.59154943e-01 5.85498315e-02 3.69163524e-17]
 [5.85498315e-02 1.59154943e-01 2.21033492e-12]
 [2.21033492e-12 3.69163524e-17 4.48939503e-54]
 [1.96412803e-05 1.79105293e-08 1.05673745e-36]
 [1.79105293e-08 2.21033492e-12 5.92068480e-45]
 [3.69163524e-17 2.21033492e-12 1.59154943e-01]
 [1.35807671e-17 8.13136774e-13 5.85498315e-02]
 [5.92068480e-45 1.05673745e-36 1.79105293e-08]]

In [45]:
a = np.arange(9).reshape(3, 3)

print(np.diag(a))
# 0 all non diagonal elements
a = np.diag(np.diag(a))
print(a)

[0 4 8]
[[0 0 0]
 [0 4 0]
 [0 0 8]]


In [47]:
a = np.arange(5)
print(a)
print(a[:, np.newaxis])
print(a[np.newaxis, :])
print(a[:, None])

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [29]:
a = np.arange(24).reshape(4, -1) 
print(a)
a = a.reshape(2,2,3,2)
print(a)
a = a.min(axis=(1,3))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]]
[[ 0  2  4]
 [12 14 16]]


In [40]:
a = np.arange(24).reshape(4, -1) 
print(a)
# group 2 by 2 example a[0][0] = [[0,1],[6,7]]
a = a.reshape(2,2,3,2).transpose(0,2,1,3)
print(a.shape)
print(a.min(axis=(2,3)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(2, 3, 2, 2)
[[ 0  2  4]
 [12 14 16]]


In [50]:
b = np.arange(24).reshape(4, 6) 
print(b)

b = b.reshape(2,2,6)
print(b)

b = b.transpose(0,2,1)
print(b)
print(b.min(axis=2))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
[[[ 0  6]
  [ 1  7]
  [ 2  8]
  [ 3  9]
  [ 4 10]
  [ 5 11]]

 [[12 18]
  [13 19]
  [14 20]
  [15 21]
  [16 22]
  [17 23]]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]


In [66]:
a = [1,2,3]
b = [4,5,6]

ab = np.vstack((a, b))
print(ab.transpose())
ab = np.array(sorted(ab, key=lambda x: x[0]))
print(ab)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [74]:
a = np.arange(6).reshape(2,3)
print(a)
print(a.mean(axis=0))
print(a.mean(axis=0).reshape(-1, 1))
print(a.T- a.mean(axis=0).reshape(-1, 1))

[[0 1 2]
 [3 4 5]]
[1.5 2.5 3.5]
[[1.5]
 [2.5]
 [3.5]]
[[-1.5  1.5]
 [-1.5  1.5]
 [-1.5  1.5]]


In [15]:
a = np.array([[0,2],[1,1],[2,0]]).T
print(a)
X = a - a.mean(axis=1).reshape(-1, 1)
print(X)
cov = X @ X.T / a.shape[1]
print(cov)
print(np.cov(a,ddof=0))

[[0 1 2]
 [2 1 0]]
[[-1.  0.  1.]
 [ 1.  0. -1.]]
[[ 0.66666667 -0.66666667]
 [-0.66666667  0.66666667]]
[[ 0.66666667 -0.66666667]
 [-0.66666667  0.66666667]]


In [20]:
a = np.array([[0,2],[1,1],[2,0]]).T
print(a)
print(np.linalg.norm(a, axis=0))

print(a / np.linalg.norm(a, axis=0))

[[0 1 2]
 [2 1 0]]
[2.         1.41421356 2.        ]
[[0.         0.70710678 1.        ]
 [1.         0.70710678 0.        ]]
